DATA SUSPENSION;
    SET 
        ESCOBS.SUSPENSION_201408
        ESCOBS.SUSPENSION_201409
        ESCOBS.SUSPENSION_201410
        ESCOBS.SUSPENSION_201411
        ESCOBS.SUSPENSION_201412
        ESCOBS.SUSPENSION_201501
        ESCOBS.SUSPENSION_201502;
RUN;

PROC SQL;
    CREATE TABLE REPORT.CLASSE AS SELECT
        A.*,
        B.CD_CUSTOMER_BOND_KIND AS ESPECIE,
        B.NR_CUSTOMER_BOND AS TITULO,
        B.NR_CUSTOMER_ITEM AS PARCELA,
        /*SUM(B.BOND_ORIGINAL_VALOR) AS VALOR*/
        B.BOND_ORIGINAL_VALOR

    FROM REPORT.TB_FEB_02 AS A 
        LEFT JOIN WORK.SUSPENSION AS B ON A.IDCONTRACT=B.CONTRATO AND A.DTSUSPENSION = B.DATA_SUSPENSAO
            /*WHERE B.BOND_ORIGINAL_VALOR < 75.99*/

    /*GROUP BY 1,2,3*/;
RUN;

PROC SORT 
    DATA=WORK.CLASSE 
    NODUPKEY;
    BY IDCONTRACT;
RUN;

PROC SQL;
    CREATE TABLE CLASSE_FINAL AS SELECT
        IDCLIENTE,
        DTSUSPENSION,
        TECHNOLOGY_TYPE,
        TIPO,
        ESPECIE,
        TITULO,
        PARCELA,
        BOND_ORIGINAL_VALOR,
        COUNT(IDCONTRACT) AS QUANT_CONTRATO
    FROM REPORT.CLASSE  AS A
        GROUP BY 1,2,3,4,5,6,7,8;
RUN;