%LET _CLIENTTASKLABEL='CRIA_MOBIL';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
%LET MISDATE = '13FEB2013'D;
PROC SQL; /*CRIA MOBIL*/
	CREATE TABLE WORK.MOBIL AS
		SELECT 
			A.ACCT_NUM AS CONTA,
			A.LOCATION_CODE AS LOCATE,
			A.ORIGINAL_TERM AS DIAS,
			A.PHONE_NUMBER_DATA_1 AS CELULAR1,
			A.PHONE_NUMBER_DATA_2 AS CELULAR2,
			substr (a.PHONE_NUMBER_DATA_1,5,1) as FONE1,
			substr (a.PHONE_NUMBER_DATA_2,5,1) as FONE2
		FROM NWBRRCON.DRI_076_R_CACS_EXT_PRI_DG3 AS A
		WHERE A.MIS_DATE = &MISDATE
		AND A.ACCT_NUM LIKE "CL%";
		
RUN;


GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

%LET _CLIENTTASKLABEL='FORMAT_PHONE';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
DATA WORK.MOBIL;/*CRIA PHONE SIM/NÃO*/
SET WORK.MOBIL;
FORMAT PHONE $3.;

IF FONE1 >= "6"  THEN	PHONE = "SIM";

IF FONE2 <= "6"  THEN PHONE = "NÃO";
ELSE PHONE = "SIM";

RUN;

GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

%LET _CLIENTTASKLABEL='CRIA_DPD';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
DATA WORK.MOBIL; /*CRIA E ALTERAR DPD*/
SET WORK.MOBIL;
	FORMAT DPD $2.;
	IF DIAS >= 0 AND  DIAS <= 29 THEN DO;
		DPD = "B1";
		END;
	ELSE
	IF DIAS >= 30 AND  DIAS <= 59 THEN DO;
		DPD = "B2";
		END;
	ELSE
	IF DIAS >= 60 AND  DIAS <= 89 THEN DO;
			DPD = "B3";
		END;
	ELSE
	IF DIAS >= 90 AND  DIAS <= 119 THEN DO;
			DPD = "B4";
		END;
	ELSE
	IF DIAS >= 120 AND  DIAS <= 149 THEN DO;
			DPD = "B5";
			END;
	ELSE
	IF DIAS >= 150 AND  DIAS <= 179 THEN DO;
			DPD = "B6";
			END;
	ELSE
	IF DIAS >= 180 THEN DO;
			DPD = "EXT";
			END;
WHERE DIAS IS NOOT NULL; 
RUN;

GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

%LET _CLIENTTASKLABEL='CRIA_BUSINESS';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
DATA WORK.MOBIL;/*CRIAR BUSINESS*/
SET WORK.MOBIL;
FORMAT BUSINESS $10.;

	IF LOCATE = "010701" THEN BUSINESS = "CF";
	
	IF LOCATE = "010101" THEN  BUSINESS = "CB";

	WHERE BUSINESS IS NOOT NULL; 
RUN;


GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

%LET _CLIENTTASKLABEL='RESUMO';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
PROC SQL;
CREATE TABLE WORK.RESUMO AS
SELECT
A.DPD,
A.BUSINESS,
A.PHONE,
COUNT(A.CONTA) AS QTD
FROM WORK.MOBIL AS A
GROUP BY 1,2,3;
WHERE BUSINESS IS NOOT NULL; 
RUN;



GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

