%LET _CLIENTTASKLABEL='RESUMO';
%LET _CLIENTPROJECTPATH='G:\AR_CB&CF.egp';
%LET _CLIENTPROJECTNAME='AR_CB&CF.egp';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
PROC SQL;
CREATE TABLE WORK.RESUMO AS
SELECT
A.DPD,
A.BUSINESS,
A.PHONE,
COUNT(A.CONTA) AS QTD
FROM WORK.MOBIL AS A
GROUP BY 1,2,3;
WHERE BUSINESS IS NOOT NULL; 
RUN;



GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

