DATA ESCOBS.CACHE_SUSPENSAO;
    SET 
        ESCOBS.SUSPENSION_201502
        ESCOBS.SUSPENSION_201503
        ESCOBS.SUSPENSION_201504;

    IF DATA_SUSPENSAO EQ . THEN
        DELETE;

    IF CD_REASON NE "318" AND CD_REASON NE "230" THEN
        DELETE;
    RENAME 
        CD_CUSTOMER_BOND_KIND =  ESPECIE
        NR_CUSTOMER_BOND = NU_BOND
        NR_CUSTOMER_ITEM = NU_BOND_ITEM
        DT_CUSTOMER_BOND_DUE_DATE = DATA_VENCIMENTO
        BOND_ORIGINAL_VALOR = VLR_BOND;
    FORMAT 
        DATA_SUSPENSAO 
        DT_CUSTOMER_BOND_DUE_DATE 
        DATA_ATIVACAO DDMMYY10.;
    KEEP 
        CLIENTE 
        CONTRATO
        ESPECIE
        DATA_SUSPENSAO
        DATA_VENCIMENTO 
        VLR_BOND
        DATA_BASE
        CENTRO_CUSTO
        TIT_PARC
        DT_DEACT
        DT_REAT
        BILLING
        LOCAL
        SCORE
        GRUPO_PLANO;
RUN;
DATA ESCOBS.CACHE_REATIVACAO;
    SET       
        ESCOBS.SUSPENSION_201502
        ESCOBS.SUSPENSION_201503
        ESCOBS.SUSPENSION_201504;

    IF DATA_SUSPENSAO NE . THEN
        DELETE;
    RENAME 
        CD_CUSTOMER_BOND_KIND =  ESPECIE
        NR_CUSTOMER_BOND = NU_BOND
        NR_CUSTOMER_ITEM = NU_BOND_ITEM
        DT_CUSTOMER_BOND_DUE_DATE = DATA_VENCIMENTO
        BOND_ORIGINAL_VALOR = VLR_BOND;
    FORMAT 
        DATA_SUSPENSAO 
        DT_CUSTOMER_BOND_DUE_DATE 
        DATA_ATIVACAO 
        DATA_REATIVACAO_ANTERIOR 
        DATA_REATIVACAO_NO_MES 
        DATA_REATIVACAO DDMMYY10.;
    KEEP 
        CLIENTE 
        CONTRATO 
        DATA_BASE 
        DATA_REATIVACAO_ANTERIOR 
        DATA_REATIVACAO_NO_MES;
RUN;