DATA SCORE;
SET ESCOBS.BDESCOB_201406;
WHERE BASE = 'REMESSA'
AND BILLING IN('BILLING_02' 'BILLING_03' 'BILLING_05' 'BILLING_10')	;
RUN;

PROC SQL;
CREATE TABLE SASUSER.ENVIO_SCORE AS 
SELECT 	DISTINCT

A.C_DLETRA,
A.C_CODI,
A.FILLER,
A.C_TIPO,
A.C_NUMT,
A.C_FILIAL,
A.C_TOTPAR,
A.C_PARCI,
A.C_PARCF,
A.C_VENCIM,
A.C_VPAR,
A.C_VTPAR,
A.C_OPERESP,
A.C_OBSE,
A.C_ID_EMP,
A.C_DATRET,
A.C_DATEMI,
A.P_SITUAC,
A.FILLER2,
A.C_CREDOR,
A.C_DT_DESATIV,
A.C_DT_SUSPENSAO,
A.C_NEGATIVADO,
A.C_DT_NEGATIVACAO,
A.C_CENTRO_CUSTO,
A.C_SOCIO1,
A.C_PER_SOCIO1,
A.C_SOCIO2,
A.C_PER_SOCIO2,
A.C_SOCIO3,
A.C_PER_SOCIO3,
A.C_RENDA,
A.C_CAP_SOCIAL,
A.C_DT_FUND,
A.C_CONTATO_1,
A.C_FONE_1_1,
A.C_FONE_2_1,
A.C_FONE_3_1,
A.C_CONTATO_2,
A.C_FONE_1_2,
A.C_FONE_2_2,
A.C_FONE_3_2,
A.C_CONTATO_3,
A.C_FONE_1_3,
A.C_FONE_2_3,
A.C_FONE_3_3,
A.C_CONTATO_1_1,
A.C_FONE_NEXTEL_1,
A.C_CONTATO_2_2,
A.C_FONE_NEXTEL_2,
A.C_CONTATO_3_3,
A.C_FONE_NEXTEL_3,
A.C_MOTIVO_BXA,
A.FILLER3,
A.ESCOB,
A.BILLING,
B.SCORE

FROM WORK.SCORE AS A LEFT JOIN WORK.BASE_SCORE AS B ON A.C_CODI = B.CLIENTE	
WHERE ESCOB = 'A1SOLUCOES';
RUN;

PROC SQL;
CREATE TABLE SCORE AS
SELECT

CPF_CGC AS CLIENTE,
CUSTOMER_COSTCENTER AS CUSTOMER,
CONTRATO AS CONTRACT,
CREDIT_SCORE_ATUAL AS SCORE

FROM ATIVA.BASE_ATIVA_201404 AS A
WHERE STATUS_CONTRATO = 'Ativo'	;

RUN;
