PROC SQL; /*BASE AGENCIAS*/
    CREATE TABLE REPORT.BASE_ATIVA AS
        SELECT

            CPF_CGC AS CLIENTE,
            CUSTOMER_COSTCENTER AS CUSTOMER,
            CONTRATO AS CONTRACT,
            TELEFONE_CONTRATO AS TELEFONE,
            PLANO AS PLANO,
            TECHNOLOGY_TYPE AS TECNOLOGIA,
            CREDIT_SCORE_ATUAL AS SCORE  
        FROM ESCOBS.BASE_ATIVA_201407 AS A
            WHERE STATUS_CONTRATO <> 'Desativado';
RUN;

DATA REPORT.BASE_ATIVA;
    SET REPORT.BASE_ATIVA;
    PLANO = UPCASE(PLANO);

    IF  TECNOLOGIA = 'IDEN' THEN
        TECNOLOGIA = '2G';

    IF SUBSTR(PLANO,1,2) = '4G' THEN             
        TECNOLOGIA = '4G';
RUN;

