
/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Wednesday, April 29, 2015 at 8:24:29 PM
   By task:     Import Data Wizard
   
   Source file: M:\titulos\RelTituloVsContrato_20150401.txt
   Server:      Local File System
   
   Output data: WORK.RelTituloVsContrato_20150401
   Server:      Local
   -------------------------------------------------------------------- */

DATA WORK.RelTituloVsContrato_20150401;
    LENGTH
        F1                 8
        F2               $ 12
        F3                 8
        F4                 8
        F5               $ 2
        F6               $ 9
        F7                 8
        F8                 8
        F9                 8
        F10              $ 1
        F11              $ 1
        F12                8
        F13              $ 29
        F14              $ 3
        F15                8
        F16                8
        F17                8
        F18              $ 1
        F19                8
        F20              $ 1 ;
    FORMAT
        F1               BEST14.
        F2               $CHAR12.
        F3               BEST6.
        F4               BEST1.
        F5               $CHAR2.
        F6               $CHAR9.
        F7               BEST8.
        F8               BEST5.
        F9               DDMMYY10.
        F10              $CHAR1.
        F11              $CHAR1.
        F12              BEST8.
        F13              $CHAR29.
        F14              $CHAR3.
        F15              DDMMYY10.
        F16              DDMMYY10.
        F17              DDMMYY10.
        F18              $CHAR1.
        F19              DDMMYY10.
        F20              $CHAR1. ;
    INFORMAT
        F1               BEST14.
        F2               $CHAR12.
        F3               BEST6.
        F4               BEST1.
        F5               $CHAR2.
        F6               $CHAR9.
        F7               BEST8.
        F8               BEST5.
        F9               DDMMYY10.
        F10              $CHAR1.
        F11              $CHAR1.
        F12              BEST8.
        F13              $CHAR29.
        F14              $CHAR3.
        F15              DDMMYY10.
        F16              DDMMYY10.
        F17              DDMMYY10.
        F18              $CHAR1.
        F19              DDMMYY10.
        F20              $CHAR1. ;
    INFILE 'C:\Users\emot2\AppData\Local\Temp\SEG164\RelTituloVsContrato_20150401-7a9f1955e3bd42f8b4e16384e4132f77.txt'
        LRECL=146
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='7F'x
        MISSOVER
        DSD ;
    INPUT
        F1               : ?? BEST14.
        F2               : $CHAR12.
        F3               : ?? BEST6.
        F4               : ?? BEST1.
        F5               : $CHAR2.
        F6               : $CHAR9.
        F7               : ?? COMMA8.
        F8               : ?? COMMA5.
        F9               : ?? DDMMYY10.
        F10              : $CHAR1.
        F11              : $CHAR1.
        F12              : ?? BEST8.
        F13              : $CHAR29.
        F14              : $CHAR3.
        F15              : ?? DDMMYY10.
        F16              : ?? DDMMYY10.
        F17              : ?? DDMMYY10.
        F18              : $CHAR1.
        F19              : ?? DDMMYY10.
        F20              : $CHAR1. ;
RUN;


