PROC SQL;
    CREATE TABLE DEACTS AS SELECT

        A.*,
        B.PLANO

    FROM ESCOBS.PRECHURN_201502_BX AS A 
        LEFT JOIN PLANO_DEACTS AS B ON A.IDCONTRACT=B.IDCONTRACT AND A.IDCLIENTE=B.IDCLIENTE
            WHERE A.IDCONTRACT IS NOT NULL;
RUN;

PROC SQL;
    CREATE TABLE DEACTS_FINAL AS SELECT 

        A.IDCLIENTE,
        A.IDCONTRACT,
        A.DTSUSPENSION ,
        SEGMENTO ,
        TECNOLOGIA


    FROM DEACTS AS A LEFT JOIN PLANO AS B ON A.plano=B.DESC_PLANO
        /*WHERE B.PLANO IS NOT NULL*/;
RUN;

DATA PLANO;
    SET ESCOBS.PLANO_201502;
    RENAME PLANO = SEGMENTO;
RUN;

DATA BASE_PLANO;
    SET ESCOBS.BASE_ATIVA_201412;
    PLANO = UPCASE(PLANO);
    IDCLIENTE = INPUT(cpf_cnpj,BEST16.);
    IDCONTRACT = INPUT(contrato,BEST8.);
    KEEP 
        PLANO IDCLIENTE IDCONTRACT status_contrato;
RUN;

PROC SQL;
    CREATE TABLE PLANO_DEACTS AS SELECT

        PLANO,
        IDCLIENTE ,
        IDCONTRACT,
        status_contrato


    FROM BASE_PLANO AS A
        WHERE status_contrato NE 'Desativado';
RUN;