PROC SQL; /*BASE AGENCIAS*/
    CREATE TABLE REPORT.BASE_ATIVA AS
        SELECT

            CPF_CNPJ AS CLIENTE,
            CUSTOMER_COSTCENTER AS CUSTOMER,
            CONTRATO AS CONTRACT,
            TELEFONE_CONTRATO AS TELEFONE,
            PLANO AS PLANO,
            TECHNOLOGY_TYPE AS TECNOLOGIA,
            CREDIT_SCORE_ATUAL AS SCORE,
            status_contrato 

        FROM ESCOBS.BASE_ATIVA_201410 AS A
            WHERE status_contrato  <> 'Desativado';
RUN;

DATA REPORT.BASE_ATIVA;
    SET REPORT.BASE_ATIVA;
    FORMAT TIPO $15.;
    PLANO = UPCASE(PLANO);

    IF PLANO IN("004/INTERNET MODEM P" "004/INTERNET MODEM P PROMO" "004/POS/SMP - INTERNET MODEM" "005/INTERNET MODEM M" "005/INTERNET MODEM M PROMO" "007/INTERNET MODEM GG" "INTERNET MODEM GG -016/PÓS/SMP" "INTERNET MODEM TESTE" "003/POS/SMP - INTERNET MODEM" "INTERN MODEM G PJ 017/PÓS/SMP" "INTERN MODEM GG PJ 016/PÓS/SMP" "INTERN MODEM M PJ 018/PÓS/SMP" "INTERN MODEM P PJ 019/PÓS/SMP" "INTERN TABLET PJ 015/PÓS/SMP" "INTERNET MODEM FF 005/PÓS/SMP" "INTERNET MODEM G - 006/PÓS/SMP" "INTERNET MODEM GG -007/PÓS/SMP" "INTERNET MODEM M - 005/PÓS/SMP" "INTERNET MODEM P - 004/PÓS/SMP" "INTERNET TABLET - 008/PÓS/SMP" "INTERNET MODEM P PROMO**" "INTERNET MODEM P" "INTERNET MODEM M PROMO**" "INTERNET MODEM M" "INTERNET MODEM G PROMO**" "INTERNET MODEM G" "INTERNET MODEM GG PROMO**" "INTERNET MODEM GG" "3G MODEM 1 GB" "3G + INT MODEM 3GB" "3G + INT MODEM 5GB" "3G +INT MODEM 8GB" "3G + INT MODEM 10GB" "4G INT MODEM 3GB" "4G INT MODEM 5GB" "4G INT MODEM 8GB" "4G INT MODEM 10GB" ) THEN
          TIPO = 'MODEM';
    ELSE  TIPO = 'NULL';

    IF  TECNOLOGIA = 'IDEN' THEN
        TECNOLOGIA = '2G';

    IF SUBSTR(PLANO,1,2) = '4G' THEN
        TECNOLOGIA = '4G';
RUN;
PROC SQL;
    DELETE FROM REPORT.BASE_ATIVA
        WHERE CUSTOMER = '';
RUN;
