/* BASE PARA CRIAÇÃO DO PRECHURN M2*/
%LET CAMINHO   = '\\BRSLP1W8PFS03\Grupos\Afinidade\Planejamento_Credito_Cobranca\035_SUSPENSION DETAIL NEW\Nextel\201504\CONSOL_01.04.TXT';
%LET BASE= PRECHURN_M2;
%LET MES=  ESCOBS.DETAILS_INICIAL_201505;
DATA &BASE;/*UPLOAD DO ARQUIVO BACKLOG - SUSPENSION DETAILS*/
    LENGTH
        INAR_RATE_PLAN $ 14
        CONTRACT_STATUS $ 15
        SUSPENSION_DATE $ 15
        CONTRACT_REASON_STATUS $ 22
        REASON           $ 23
        CUSTOMER_NAME $ 41
        CUSTOMER_TAX_NUMBER $ 19
        CONTRACT         $ 8
        TECHNOLOGY_TYPE $ 15
        SEGMENTATION     $ 12
        ORGANIZATION_TYPE $ 17
        CREDIT_SCORE  $ 12
        CUSTOMER_TENURE $ 17;
    FORMAT
        INAR_RATE_PLAN  $CHAR14.
        CONTRACT_STATUS $CHAR15.
        SUSPENSION_DATE $CHAR15.
        CONTRACT_REASON_STATUS $CHAR22.
        REASON           $CHAR23.
        CUSTOMER_NAME $CHAR41.
        CUSTOMER_TAX_NUMBER $CHAR19.
        CONTRACT         $CHAR8.
        TECHNOLOGY_TYPE $CHAR15.
        SEGMENTATION     $CHAR12.
        ORGANIZATION_TYPE $CHAR17.
        CREDIT_SCORE  $CHAR12.
        CUSTOMER_TENURE $CHAR17.;
    INFORMAT
        INAR_RATE_PLAN $CHAR14.
        CONTRACT_STATUS $CHAR15.
        SUSPENSION_DATE $CHAR15.
        CONTRACT_REASON_STATUS $CHAR22.
        REASON           $CHAR23.
        CUSTOMER_NAME $CHAR41.
        CUSTOMER_TAX_NUMBER $CHAR19.
        CONTRACT         $CHAR8.
        TECHNOLOGY_TYPE $CHAR15.
        SEGMENTATION     $CHAR12.
        ORGANIZATION_TYPE $CHAR17.
        CREDIT_SCORE  $CHAR12.
        CUSTOMER_TENURE $CHAR17.;
    INFILE &CAMINHO
        LRECL=1122
        ENCODING="WLATIN1"
        DLM=";";
    INPUT
        INAR_RATE_PLAN: $CHAR14.
        CONTRACT_STATUS : $CHAR15.
        SUSPENSION_DATE : $CHAR15.
        CONTRACT_REASON_STATUS : $CHAR22.
        REASON           : $CHAR23.
        CUSTOMER_NAME : $CHAR41.
        CUSTOMER_TAX_NUMBER : $CHAR19.
        CONTRACT         : $CHAR8.
        TECHNOLOGY_TYPE : $CHAR15.
        SEGMENTATION     : $CHAR12.
        ORGANIZATION_TYPE : $CHAR17.
        CREDIT_SCORE  : $CHAR12.
        CUSTOMER_TENURE : $CHAR17.;
RUN;
PROC SQL;
    DELETE FROM PRECHURN_M2
        WHERE SUSPENSION_DATE = "Suspension Date";
RUN;
DATA PRECHURN_M2;
    SET PRECHURN_M2;
    FORMAT DT_DEACT DDMMYY10.;
    FORMAT DTSUSPENSION DDMMYY10.;
    INFORMAT DTSUSPENSION DDMMYY10.;
    LENGTH DTSUSPENSION 8;
    FORMAT IDCLIENTE 14.;
    DTSUSPENSION = INPUT(SUSPENSION_DATE, DDMMYY10.);
    IDCONTRACT  = INPUT(CONTRACT,BEST8.)*1;
    IDCLIENTE = INPUT(CUSTOMER_TAX_NUMBER, BEST14.)*1;
    CD_REASON = INPUT(CONTRACT_REASON_STATUS,BEST3.)*1;

    IF TECHNOLOGY_TYPE = 'IDEN' THEN
        DO;
            IF CONTRACT_REASON_STATUS = 318 THEN
                DT_DEACT = DTSUSPENSION + 60;
        END;

    IF TECHNOLOGY_TYPE = '3G' THEN
        DO;
            IF CONTRACT_REASON_STATUS=318 THEN
                DT_DEACT = DTSUSPENSION + 75;

            IF CONTRACT_REASON_STATUS=230 THEN
                DT_DEACT = DTSUSPENSION + 45;
        END;
RUN;
PROC APPEND 
    DATA=WORK.PRECHURN_M2
    BASE=&MES
    FORCE;
RUN;
PROC FREQ 
    DATA=&MES;
    TABLE DTSUSPENSION;
RUN;
