PROC SQL;
    CREATE TABLE PARTE_1 AS SELECT 

        A.*,
        B.  contract

    FROM ESCOBS.PRECHURN_201503_BX AS A  LEFT JOIN   WORK.BASE_CRIS AS B   ON   A.IDCONTRACT  =B.contract
        WHERE  B.  contract  IS   NULL;
RUN;

PROC SQL;
    *4.SALDO RECUPERADO CRUZANDO COM O REATIVADO;
    CREATE TABLE PARTE_2  AS
        SELECT DISTINCT
            A.*,
            B.DATA_BASE AS DT_REAT

        FROM PARTE_1 AS A 
            LEFT JOIN ESCOBS.CACHE_REATIVACAO AS B ON A.IDCLIENTE = B.CLIENTE AND A.IDCONTRACT = B.CONTRATO 
                AND B.DATA_BASE BETWEEN INPUT('01/03/2015', DDMMYY10.) AND INPUT('31/03/2015', DDMMYY10.)
                AND  (B.DATA_REATIVACAO_NO_MES = A.DTSUSPENSION OR B. DATA_REATIVACAO_ANTERIOR = A.DTSUSPENSION)
            WHERE (1=1)
                AND B.DATA_BASE IS NOT NULL;
RUN;

PROC SORT DATA  = PARTE_2;
    BY IDCONTRACT  IDCLIENTE 
        DESCENDING DTSUSPENSION;
RUN;

PROC SORT DATA  = PARTE_2  
    NODUPKEY;
    BY IDCLIENTE IDCONTRACT;
RUN;

PROC SQL;
    CREATE TABLE PARTE_3 AS SELECT 

        A.*,
        B.  contract

    FROM ESCOBS.PRECHURN_201503 AS A  INNER  JOIN   WORK.PARTE_1 AS B   ON   A.IDCONTRACT  =B.contract
        WHERE  B.  contract  IS  NOT  NULL;
RUN;