PROC SQL;    
    CREATE TABLE WORK.CONCORRENCIA_CARTOES AS SELECT DISTINCT 


        A.DESCR_OPERADORA,
        PUT(A.DT_ENVIO,DATE9.) AS DT_ENVIO,
        COUNT(A.CELULAR) AS QTDE_CELULAR


    FROM CARTAO.SMS_ENVIO_OPERADORA AS A

    GROUP BY 1,2;
RUN;

DATA WORK.CONCORRENCIA_CARTOES;
    SET WORK.CONCORRENCIA_CARTOES;
    DATA_ENVIO = SUBSTR(DT_ENVIO,3,7);
RUN;

PROC SQL;
    CREATE TABLE WORK.CARTAO AS SELECT 

        A.DESCR_OPERADORA,
        A.DATA_ENVIO,
        SUM(A.QTDE_CELULAR) AS QTDE


    FROM WORK.CONCORRENCIA_CARTOES AS A

    GROUP BY 1,2;
RUN;
