PROC SQL;/*GERAR TABLE TEMP*/
 CREATE TABLE SASUSER.AC_CARDS_TEMP AS SELECT DRI_076_ECS_AMBS_ED.EDW_BS_LIQ_DATE FORMAT=DATETIME20.,
	 (COUNT(DRI_076_ECS_AMBS_ED.EDW_BS_CUST_NBR)) AS BS_CUST_NBR,
	 DRI_076_ECS_AMBS_ED.EDW_BS_ORG FORMAT=4. 
 FROM BRDBCON.DRI_076_ECS_AMBS_ED AS DRI_076_ECS_AMBS_ED
 WHERE ( DRI_076_ECS_AMBS_ED.EDW_BS_USER_CODE_6 = "LL" AND ( DRI_076_ECS_AMBS_ED.MIS_DATE = '29FEB2012:00:00:00'dt 
 AND DRI_076_ECS_AMBS_ED.EDW_BS_LIQ_DATE BETWEEN '01FEB2012:00:00:00'dt and '29FEB2012:00:00:00'dt ) )
 GROUP BY DRI_076_ECS_AMBS_ED.EDW_BS_ORG, DRI_076_ECS_AMBS_ED.EDW_BS_LIQ_DATE
 ORDER BY BS_CUST_NBR, DRI_076_ECS_AMBS_ED.EDW_BS_LIQ_DATE;
QUIT;
PROC SQL;/*RESULTADO FINAL*/
 CREATE TABLE SASUSER.AC_CARDS AS SELECT (SUM(AC_CARDS_TEMP.BS_CUST_NBR)) AS AC_CARDS 
 FROM SASUSER.AC_CARDS_TEMP AS AC_CARDS_TEMP;
RUN;
PROC DATASETS/* DROP TABLE */

LIB = SASUSER;

DELETE AC_CARDS_TEMP;

RUN;