*CRIACAO DO BDCONTRACT;
PROC SQL;
    CREATE TABLE REPORT.BD_TITULO  AS SELECT DISTINCT

        IDCLIENTE AS CPF,
        VENC_TITULO FORMAT DDMMYY10. AS VENC,
        TITULO,
        ESPECIE,
        CENTRO_CUSTO
    FROM REPORT.REMESSA AS A
        WHERE P_SITUAC = "ENV"
            AND BASE = 'REMESSA'
        GROUP BY 1,2,3,4,5;
RUN;

PROC SQL;
    CREATE TABLE REPORT.BD_CONTRATO  AS SELECT DISTINCT

        IDCLIENTE AS C_CPF ,
        DATA_VENC AS VENCIMENTO,
        ESPECIE,
        P_TITULO,
        CENTRO_CUSTO,
        CONTRATO

    FROM ESCOBS.BDCONTRACT AS A;
RUN;

PROC SQL;
    CREATE TABLE REPORT.BD_CONTRACT AS SELECT  DISTINCT
        A.*,
        B.CONTRATO,
        B.DT_DEACTS

    FROM REPORT.BD_TITULO AS A LEFT JOIN REPORT.DEACTS  AS B
        ON A.CPF=B.C_CPF AND A.VENC=B.VENCIMENTO AND A.R_TITULO=B.P_TITULO AND A.ESPECIE=B.ESPECIE
    WHERE DT_DEACTS = .;
RUN;

*AGRUPANDO QUANTIDADE DE TITUTLO + REMESSA;
PROC SQL;
    CREATE TABLE REPORT.FINAL_01 AS SELECT DISTINCT

        CPF,
        VENC,
        R_TITULO,
        ESPECIE
    FROM REPORT.BD_CONTRACT AS A
        GROUP BY 3;
RUN;

PROC SQL;
    CREATE TABLE REPORT.FINAL_02 AS SELECT DISTINCT

        CPF,
        VENC,
        COUNT(R_TITULO) AS QUANT_TITULO,
        ESPECIE

    FROM REPORT.FINAL_01 AS A
        GROUP BY 1,2,4;
RUN;

PROC SQL;
    CREATE TABLE REPORT.FINAL_03 AS SELECT DISTINCT

        CPF,
        VENC,
        CONTRATO,
        ESPECIE
    FROM REPORT.BD_CONTRACT AS A
        GROUP BY 3;
RUN;

PROC SQL;
    CREATE TABLE REPORT.FINAL_04 AS SELECT DISTINCT

        CPF,
        VENC,
        COUNT(CONTRATO) AS QUANT_CONTRATO,
        ESPECIE

    FROM REPORT.FINAL_03 AS A
        GROUP BY 1,2,4;
RUN;

PROC SQL;
    CREATE TABLE REPORT.FINAL AS SELECT DISTINCT

        A.*,
        B.QUANT_TITULO


    FROM REPORT.FINAL_04 AS  A INNER JOIN  REPORT.FINAL_02  AS B  ON A.CPF=B.CPF
    ;
RUN;