
PROC SQL;
DELETE FROM ESCOBS.BDPRESTACAO_201405
WHERE DATA_ARQUIVO = '07MAY2014'D
AND ESCOB  = 'EMPRESARIO';

RUN;

PROC SQL;
DELETE FROM ESCOBS.BDPRESTACAO_201405
WHERE P_DLETRA = ''
;

RUN;

DATA TESTE;
SET ESCOBS.BDPRESTACAO_201402;
IF DATA_ARQUIVO = '14FEB2014'D 	THEN  DATA_ARQUIVO = '13FEB2014'D
;

RUN;

PROC TABULATE 
DATA = 	ESCOBS.BDESCOB_201405				MISSING FORMAT = COMMAX15.	ORDER = FORMATTED;	
TITLE	CONTAGEM;																
CLASS	BASE DATA_ARQUIVO ESCOB;																
TABLE	DATA_ARQUIVO='' ALL,	ESCOB*BASE=''*N=''	ALL*N='';						
KEYLABEL ALL = 'TOTAL';
RUN;

PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201405
WHERE DATA_ARQUIVO = '07MAY2014'D
AND BASE  = 'REMESSA COMP'
AND ESCOB = 'ULTRACENTER';
RUN;

PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201403
WHERE BASE IN ('REMESSA' 'REMESSA COMP')
AND DATA_ARQUIVO = '06MAR2014'D
AND ESCOB = 'A1SOLUCOES'
;

RUN;

DATA TESTE_DUP;
SET ESCOBS.BDESCOB_201402;	
WHERE BASE IN ('REMESSA' 'REMESSA COMP');
RUN; 

PROC SORT DATA = TESTE_DUP;
BY C_ID_EMP DATA_ARQUIVO;
RUN;

DATA BASE_FINAL;
SET TESTE_DUP;
BY C_ID_EMP;
IF FIRST.C_ID_EMP THEN CONTADOR = 1;
ELSE CONTADOR+1;
RUN;

DATA TESTE_DUP1;	
SET  BASE_FINAL;	
WHERE CONTADOR = 2;	
RUN;

DATA TESTE_DUP1;		
SET  BASE_FINAL;	
WHERE C_ID_EMP IN('33394613''33394630''33394761''33395040''33395128''33395146');
RUN;

DATA TESTE_DUP;
SET ESCOBS.BDESCOB_201402;
WHERE BASE IN ('BAIXA');
RUN; 

PROC SORT DATA = PC;
BY P_ID_EMP DATA_ARQUIVO;
RUN;

DATA BASE_FINAL;
SET PC;
BY P_ID_EMP;
        IF FIRST.P_ID_EMP THEN CONTADOR = 1;
        ELSE CONTADOR+1;
RUN;

DATA TESTE_DUP1;		
SET  BASE_FINAL;		
WHERE CONTADOR = 2;		
RUN;

DATA TESTE_DUP1;		
SET  BASE_FINAL;		
WHERE P_ID_EMP IN('31401324''31729740''31795986''31812107''31818819''31818991''31841208''31842252''31844811');
RUN;

DATA TESTE;
SET  ESCOBS.BDESCOB_201401
ESCOBS.BDESCOB_201402;
WHERE C_ID_EMP IN('32391623''32391624''32391626');
RUN;

DATA TESTE;
SET  BASE_3;
WHERE ESCOB = 'A1SOLUCOES' AND TIPO = 'PF' AND BILLING = 'BILLING_25' AND PRIOR = '';
RUN;

PROC SQL; 
CREATE TABLE VALUE AS
SELECT
	ESCOB,
	TIPO,
	DATA_ARQUIVO,
	C_CODI,
	PRIOR,
	C_ID_EMP
FROM BASE_3
WHERE BASE = 'REMESSA COMP'
AND ESCOB = 'A1SOLUCOES'
AND	DATA_ARQUIVO  = '02JAN2014'D;

RUN;

PROC SQL;
CREATE TABLE TESTE AS 
SELECT 
TITULO,
COUNT(TITULO) AS QTD
FROM BILLING
GROUP BY TITULO;
RUN;

PROC SORT DATA=TESTE;
BY DESCENDING QTD;
RUN;

PROC SQL;

ALTER TABLE ESCOBS.BDESCOB_201402 DROP COLUMN BASE_DESC;

RUN;

PROC SQL;
SELECT
ESCOB,
DATA_ARQUIVO,
C_VENCIM,
BILLING,
/*COUNT(TIPO) AS TIPO,
SUM(VALUE) AS TOTAL_VALOR*/
FROM WORK.VENC_FINAL AS A
/*GROUP BY 1,2,3,4;*/


RUN;

 DATA VENC_FINAL;
 SET VENC;

VALUE = VALOR*1;

RUN;
/*PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201402
WHERE DATA_ARQUIVO = '11FEB2014'D
AND BASE  = 'BAIXA'
AND ESCOB = 'A1SOLUCOES';
RUN;*/

PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201402
WHERE BASE IN ('REMESSA' 'REMESSA COMP')
AND DATA_ARQUIVO = '11FEB2014'D;
RUN;

PROC SQL; /*RELATORIOS - COMPLEMENTAR*/
CREATE TABLE VOLUME_REMESSA_COMP AS
SELECT
	ESCOB,
	TIPO,
	PRIOR,
	DATA_ARQUIVO,
	COUNT(TITULO) AS QTD,
	SUM(VALOR) FORMAT COMMAX9.2  AS VALOR
FROM BASE_3
WHERE BASE = 'REMESSA COMP'
AND DATA_ARQUIVO = '04FEB2014'D
GROUP BY 1,2,3,4;
RUN;  

PROC SQL;/*RELATORIOS - BILLING*/
CREATE TABLE VOLUME_REMESSA_BILLING AS
SELECT
	ESCOB,
	TIPO,
	PRIOR,
	BILLING,
	DATA_ARQUIVO,
	COUNT(TITULO) AS QTD,
	SUM(VALOR) FORMAT COMMAX9.2  AS VALOR
FROM BASE_3
WHERE BASE = 'REMESSA'
GROUP BY 1,2,3,4,5;
RUN;

PROC SQL; /*RELATORIOS - COMPLEMENTAR*/
CREATE TABLE TESTE AS	
SELECT

	C_ID_EMP,
	ESCOB,
	TIPO,
	BASE,
	DATA_ARQUIVO,
	STATUS


FROM ESCOBS.BDESCOB_201402
WHERE BASE = 'BAIXA'
AND ESCOB = 'A1SOLUCOES'
AND TIPO = 'PJ'
AND DATA_ARQUIVO = '04FEB2014'D
;
RUN; 

/PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201407
WHERE DATA_ARQUIVO = '24JUL2014'D
AND BASE IN ( 'BAIXA')
AND ESCOB = 'A1SOLUCOES';
RUN;
PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201406
WHERE BASE =  'BAIXA'
AND DATA_ARQUIVO ='30JUN2014'D
AND ESCOB = 'A1SOLUCOES';
RUN ;
PROC SQL;
DELETE FROM ESCOBS.BDESCOB_201406
WHERE DATA_ARQUIVO=  '19JUN2014'D  ;
RUN ;
DATA ESCOBS.BDESCOB_201406;
SET ESCOBS.BDESCOB_201406;
IF DATA_ARQUIVO = '16JUN2014'D AND ESCOB = 'A1SOLUCOES' THEN ESCOB = 'ULTRACENTER';
RUN;



DATA TESTE;
DO CAMINHO = 1 TO 30;
OUTPUT;
END;
RUN;

DATA _NULL_;
IF 0 THEN SET TESTE NOBS = X;
CALL SYMPUT('FIM',X);
RUN;
%PUT &FIM.;

%MACRO RODA();
%DO I = 1 %TO &FIM.;
DATA _NULL_;
	SET TESTE(FIRSTOBS=&I);
		CALL SYMPUTX('CAMINHO',CAMINHO);
	STOP;
RUN;

DATA BASE; /*IMPORTACAO DA ARQUIVO TXT*/	
    LENGTH
        C_DLETRA $ 1
	    C_CODI $ 20
	    FILLER $ 2
	    C_TIPO $ 2
	    C_NUMT $ 18
		C_FILIAL $ 5
		C_TOTPAR $ 2
		C_PARCI $ 2
		C_PARCF $ 2
		C_VENCIM $ 8
		C_VPAR $ 12
		C_VTPAR $ 12
		C_OPERESP $ 3
		C_OBSE $ 60
		C_ID_EMP $ 16
		C_DATRET $ 8
		C_DATEMI $ 8
		P_SITUAC $ 4
		FILLER2 $ 378
		C_CREDOR $ 5
		C_DT_DESATIV $ 8
		C_DT_SUSPENSAO $ 8
		C_NEGATIVADO $ 1
		C_DT_NEGATIVACAO $ 8
		C_CENTRO_CUSTO $ 50
		C_SOCIO1 $ 20
		C_PER_SOCIO1 $ 3
		C_SOCIO2 $ 20
		C_PER_SOCIO2 $ 3
		C_SOCIO3 $ 20
		C_PER_SOCIO3 $ 3
		C_RENDA $ 15
		C_CAP_SOCIAL $ 15
		C_DT_FUND $ 8
		C_CONTATO_1 $ 30
		C_FONE_1_1 $ 15
		C_FONE_2_1 $ 15
		C_FONE_3_1 $ 15
		C_CONTATO_2 $ 30
		C_FONE_1_2 $ 15
		C_FONE_2_2 $ 15
		C_FONE_3_2 $ 15
		C_CONTATO_3 $ 30
		C_FONE_1_3 $ 15
		C_FONE_2_3 $ 15
		C_FONE_3_3 $ 15
		C_CONTATO_1_1 $ 30
		C_FONE_NEXTEL_1 $ 15
		C_CONTATO_2_2 $ 30
		C_FONE_NEXTEL_2 $ 15
		C_CONTATO_3_3 $ 30
		C_FONE_NEXTEL_3 $ 15
		C_QTD_DIUL_VENC $ 5
		C_MOTIVO_BXA $ 5
		FILLER3 $ 2;
    FORMAT
		C_DLETRA CHAR1.
		C_CODI CHAR20.
		FILLER CHAR2.
		C_TIPO CHAR2.
		C_NUMT CHAR18.
		C_FILIAL CHAR5.
		C_TOTPAR CHAR2.
		C_PARCI CHAR2.
		C_PARCF CHAR2.
		C_VENCIM CHAR8.
		C_VPAR CHAR12.
		C_VTPAR CHAR12.
		C_OPERESP CHAR3.
		C_OBSE CHAR60.
		C_ID_EMP CHAR16.
		C_DATRET CHAR8.
		C_DATEMI CHAR8.
		P_SITUAC CHAR4.
		FILLER2 CHAR378.
		C_CREDOR CHAR5.
		C_DT_DESATIV CHAR8.
		C_DT_SUSPENSAO CHAR8.
		C_NEGATIVADO CHAR1.
		C_DT_NEGATIVACAO CHAR8.
		C_CENTRO_CUSTO CHAR50.
		C_SOCIO1 CHAR20.
		C_PER_SOCIO1 CHAR3.
		C_SOCIO2 CHAR20.
		C_PER_SOCIO2 CHAR3.
		C_SOCIO3 CHAR20.
		C_PER_SOCIO3 CHAR3.
		C_RENDA CHAR15.
		C_CAP_SOCIAL CHAR15.
		C_DT_FUND CHAR8.
		C_CONTATO_1 CHAR30.
		C_FONE_1_1 CHAR15.
		C_FONE_2_1 CHAR15.
		C_FONE_3_1 CHAR15.
		C_CONTATO_2 CHAR30.
		C_FONE_1_2 CHAR15.
		C_FONE_2_2 CHAR15.
		C_FONE_3_2 CHAR15.
		C_CONTATO_3 CHAR30.
		C_FONE_1_3 CHAR15.
		C_FONE_2_3 CHAR15.
		C_FONE_3_3 CHAR15.
		C_CONTATO_1_1 CHAR30.
		C_FONE_NEXTEL_1 CHAR15.
		C_CONTATO_2_2 CHAR30.
		C_FONE_NEXTEL_2 CHAR15.
		C_CONTATO_3_3 CHAR30.
		C_FONE_NEXTEL_3 CHAR15.
		C_QTD_DIUL_VENC CHAR5.
		C_MOTIVO_BXA CHAR5.
		FILLER3 CHAR2.;
    INFORMAT
        C_DLETRA $CHAR1.
		C_CODI $CHAR20.
		FILLER $CHAR2.
		C_TIPO $CHAR2.
		C_NUMT $CHAR18.
		C_FILIAL $CHAR5.
		C_TOTPAR $CHAR2.
		C_PARCI $CHAR2.
		C_PARCF $CHAR2.
		C_VENCIM $CHAR8.
		C_VPAR $CHAR12.
		C_VTPAR $CHAR12.
		C_OPERESP $CHAR3.
		C_OBSE $CHAR60.
		C_ID_EMP $CHAR16.
		C_DATRET $CHAR8.
		C_DATEMI $CHAR8.
		P_SITUAC $CHAR4.
		FILLER2 $CHAR378.
		C_CREDOR $CHAR5.
		C_DT_DESATIV $CHAR8.
		C_DT_SUSPENSAO $CHAR8.
		C_NEGATIVADO $CHAR1.
		C_DT_NEGATIVACAO $CHAR8.
		C_CENTRO_CUSTO $CHAR50.
		C_SOCIO1 $CHAR20.
		C_PER_SOCIO1 $CHAR3.
		C_SOCIO2 $CHAR20.
		C_PER_SOCIO2 $CHAR3.
		C_SOCIO3 $CHAR20.
		C_PER_SOCIO3 $CHAR3.
		C_RENDA $CHAR15.
		C_CAP_SOCIAL $CHAR15.
		C_DT_FUND $CHAR8.
		C_CONTATO_1 $CHAR30.
		C_FONE_1_1 $CHAR15.
		C_FONE_2_1 $CHAR15.
		C_FONE_3_1 $CHAR15.
		C_CONTATO_2 $CHAR30.
		C_FONE_1_2 $CHAR15.
		C_FONE_2_2 $CHAR15.
		C_FONE_3_2 $CHAR15.
		C_CONTATO_3 $CHAR30.
		C_FONE_1_3 $CHAR15.
		C_FONE_2_3 $CHAR15.
		C_FONE_3_3 $CHAR15.
		C_CONTATO_1_1 $CHAR30.
		C_FONE_NEXTEL_1 $CHAR15.
		C_CONTATO_2_2 $CHAR30.
		C_FONE_NEXTEL_2 $CHAR15.
		C_CONTATO_3_3 $CHAR30.
		C_FONE_NEXTEL_3 $CHAR15.
		C_QTD_DIUL_VENC $CHAR5.
		C_MOTIVO_BXA $CHAR5.
		FILLER3 $CHAR2. ;
        INFILE &CAMINHO
        LRECL=1122
        ENCODING="WLATIN1"
        TRUNCOVER;
    INPUT
		@1 C_DLETRA $CHAR1.
		@2 C_CODI $CHAR20.
		@22 FILLER $CHAR2.
		@24 C_TIPO $CHAR2.
		@26 C_NUMT $CHAR18.
		@44 C_FILIAL $CHAR5.
		@49 C_TOTPAR $CHAR2.
		@51 C_PARCI $CHAR2.
		@53 C_PARCF $CHAR2.
		@55 C_VENCIM $CHAR8.
		@63 C_VPAR $CHAR12.
		@75 C_VTPAR $CHAR12.
		@87 C_OPERESP $CHAR3.
		@90 C_OBSE $CHAR60.
		@150 C_ID_EMP $CHAR16.
		@166 C_DATRET $CHAR8.
		@174 C_DATEMI $CHAR8.
		@182 P_SITUAC $CHAR4.
		@186 FILLER2 $CHAR378.
		@564 C_CREDOR $CHAR5.
		@569 C_DT_DESATIV $CHAR8.
		@577 C_DT_SUSPENSAO $CHAR8.
		@585 C_NEGATIVADO $CHAR1.
		@586 C_DT_NEGATIVACAO $CHAR8.
		@594 C_CENTRO_CUSTO $CHAR50.
		@644 C_SOCIO1 $CHAR20.
		@664 C_PER_SOCIO1 $CHAR3.
		@667 C_SOCIO2 $CHAR20.
		@687 C_PER_SOCIO2 $CHAR3.
		@690 C_SOCIO3 $CHAR20.
		@710 C_PER_SOCIO3 $CHAR3.
		@713 C_RENDA $CHAR15.
		@728 C_CAP_SOCIAL $CHAR15.
		@743 C_DT_FUND $CHAR8.
		@751 C_CONTATO_1 $CHAR30.
		@781 C_FONE_1_1 $CHAR15.
		@796 C_FONE_2_1 $CHAR15.
		@811 C_FONE_3_1 $CHAR15.
		@826 C_CONTATO_2 $CHAR30.
		@856 C_FONE_1_2 $CHAR15.
		@871 C_FONE_2_2 $CHAR15.
		@886 C_FONE_3_2 $CHAR15.
		@901 C_CONTATO_3 $CHAR30.
		@931 C_FONE_1_3 $CHAR15.
		@946 C_FONE_2_3 $CHAR15.
		@961 C_FONE_3_3 $CHAR15.
		@976 C_CONTATO_1_1 $CHAR30.
		@1006 C_FONE_NEXTEL_1 $CHAR15.
		@1021 C_CONTATO_2_2 $CHAR30.
		@1051 C_FONE_NEXTEL_2 $CHAR15.
		@1066 C_CONTATO_3_3 $CHAR30.
		@1096 C_FONE_NEXTEL_3 $CHAR15.
		@1111 C_QTD_DIUL_VENC $CHAR5.
		@1116 C_MOTIVO_BXA $CHAR5.
		@1121 FILLER3 $CHAR2.;
RUN;
PROC APPEND DATA=BASE BASE=BASE_FULL FORCE;RUN;
PROC SQL;
DROP TABLE BASE;
QUIT;
%END;
%MEND;
%RODA;

FILENAME TESTE PIPE "DIR C:";
DATA RRR;
INFILE TESTE;
INPUT AAA $50.;
RUN;

PROC TABULATE
DATA=WORK.VOLUME_REMESSA_BILLING

	OUT=ESCOBS.REPORT_BILLING(LABEL="ESCOB TABLES  FOR WORK.VOLUME_REMESSA_BILLING")
	
	FORMAT=COMMAX9.2
	;
	
	VAR VALOR QTD;
	CLASS TIPO /	ORDER=UNFORMATTED MISSING;
	CLASS BILLING /	ORDER=UNFORMATTED MISSING;
	CLASS PRIOR /	ORDER=UNFORMATTED MISSING;
	CLASS ESCOB /	ORDER=UNFORMATTED MISSING;
	TABLE 
		/* PAGE STATEMENT */
		ALL = 'TOTAL - BILLING'
		ESCOB  ,
		/* ROW STATEMENT */
		BILLING 
		ALL = 'TOTAL - BILLING' ,
		/* COLUMN STATEMENT */
		PRIOR *TIPO *(VALOR * SUM={LABEL="$"} QTD * SUM={LABEL="#"} )
		ALL = 'TOTAL - BILLING'  *(VALOR * SUM={LABEL="$"} QTD * SUM={LABEL="#"} ) 		;
	;

RUN;


PROC SQL ;
ALTER TABLE WORK.TESTE ADD CREDIT_SCORE CHAR ; 
RUN;


