*EQUIPE CREDIT - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M1_GRUPO_INCIAL
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\INICIAL_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
*EQUIPE CREDIT - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M2_GRUPO_INCIAL
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\INICIAL_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE CREDIT - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M1_GRUPO
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\SALDO_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE CREDIT - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M2_GRUPO
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\SALDO_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *CREDIT - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M1_TB02
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\RECUPERADO_CHURN201504.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *CREDIT - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M2_TB02
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\RECUPERADO_CHURN201505.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
*EQUIPE COLLECTION - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M1_GRUPO_INCIAL
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\INICIAL_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
*EQUIPE COLLECTION - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M2_GRUPO_INCIAL
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\INICIAL_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M1_GRUPO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\SALDO_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M2_GRUPO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\SALDO_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *COLLECTION - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M1_TB02
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\RECUPERADO_CHURN201504.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *COLLECTION - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M2_TB02
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\RECUPERADO_CHURN201505.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;

 