/*EQUIPE CREDIT - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M1_GRUPO_INCIAL
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\INICIAL_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
*EQUIPE CREDIT - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= REPORT.M2_GRUPO_INCIAL
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\INICIAL_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE CREDIT - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M1_GRUPO_SALDO
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\SALDO_CHURN201504_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE CREDIT - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M2_GRUPO_SALDO
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\SALDO_CHURN201505_C.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *CREDIT - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M1_TB02
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\04_APR_15\RECUPERADO_CHURN201504.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *CREDIT - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M2_TB02
    OUTFILE= "\\BRBLC1W7393324\SAS\PRECHURN\05_MAY_15\RECUPERADO_CHURN201505.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;  */
*EQUIPE COLLECTION - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= ESCOBS.PRECHURN_201507_AT
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\PRECHURN201507.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
*EQUIPE COLLECTION - APENAS NO INÍCIO DO MÊS;
PROC EXPORT DATA= ESCOBS.PRECHURN_201508_AT
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\PREPDD201508.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M1_GRUPO_SALDO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\S_PRECHURN201507.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
  * EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN;
PROC EXPORT DATA= REPORT.M2_GRUPO_SALDO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\S_PREPDD201508.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *COLLECTION - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M1_TB02
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\R_PRECHURN201507.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;
   *COLLECTION - SALDO RECUPERADO;
PROC EXPORT DATA= REPORT.M2_TB02
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\R_PREPDD201508.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;

   * EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN-AGOSTO;
PROC EXPORT DATA= REPORT.M3_GRUPO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\S_PREPDD201509.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;

* EQUIPE COLLECTION - SALDO EM ABERTO DO PRECHURN-SETEMBRO;
PROC EXPORT DATA= REPORT.M4_GRUPO
    OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\23_PRECHURN\PRECHURN\S_PREPDD201510.TXT" 
    DBMS=TAB 
    REPLACE;
    PUTNAMES=YES;
RUN;