
DATA ESCOBS.BDCONTRACT;
SET ESCOBS.BDCONTRACT;
P_TITULO = COMPRESS(TITULO||PARCELA)*1;
RUN;

PROC SQL;
	CREATE TABLE REPORT.BD_D2 AS SELECT
		A.*,
		B.CONTRACT_LIFE_CYCLE_START_DATE AS DT_DEACTS,
		B.DEACTS

	FROM ESCOBS.BDCONTRACT AS A LEFT JOIN ESCOBS.DEACTS_201506 AS B ON A.CONTRATO=B.CONTRACT;
RUN;

PROC SQL;
	CREATE TABLE REPORT.BD_D3 AS 
		SELECT 
			P_TITULO,
			DATA_VENC FORMAT DATE10., 
			COUNT(CONTRATO) AS CTR
		FROM REPORT.BD_D2  
			WHERE DT_DEACTS = . 
				GROUP BY P_TITULO, DATA_VENC;
RUN;
*QUANTIDADE DE CONTRATOS ESCOBS;
PROC SQL;
	CREATE TABLE REPORT.BD_D4 AS 
		SELECT    
			* 
		FROM REPORT.BASE_6 AS A
			LEFT JOIN REPORT.BD_D3  AS B ON A.P_TITULO = B.P_TITULO 
				AND A.VENC_TITULO =  B.DATA_VENC;
RUN;
PROC SQL;*QUANTIDADE DE CONTRATOS EXTRA;
	CREATE TABLE REPORT.BD_D4_EX AS 
		SELECT    
			* 
		FROM REPORT.BASE_9 AS A
			LEFT JOIN REPORT.BD_D3  AS B ON A.P_TITULO = B.P_TITULO 
				AND A.VENC_TITULO =  B.DATA_VENC;
RUN;



