PROC SQL;
    CREATE TABLE TESTE AS 
        SELECT  DISTINCT

            A.ESCOB,
            A.C_CODI AS CPF,
            A.TIPO,
            B.PLANO,
            B.TELEFONE,
            B.TECNOLOGIA



        FROM REPORT.BASE_3 AS A LEFT JOIN REPORT.BASE_ATIVA AS B ON A.CPF = B.CLIENTE
            /*WHERE PLANO IS NOT NULL*/
               /* AND TECNOLOGIA = "2G"*/
                AND PLANO IN ("004/INTERNET MODEM P" "004/INTERNET MODEM P PROMO" 
                "004/POS/SMP - INTERNET MODEM" "005/INTERNET MODEM M" "005/INTERNET MODEM M PROMO" 
                "007/INTERNET MODEM GG" "INTERNET MODEM GG -016/PÓS/SMP" "INTERNET MODEM TESTE" 
                "003/POS/SMP - INTERNET MODEM" "INTERN MODEM G PJ 017/PÓS/SMP" "INTERN MODEM GG PJ 016/PÓS/SMP" 
                "INTERN MODEM M PJ 018/PÓS/SMP" "INTERN MODEM P PJ 019/PÓS/SMP" "INTERN TABLET PJ 015/PÓS/SMP" 
                "INTERNET MODEM FF 005/PÓS/SMP" "INTERNET MODEM G - 006/PÓS/SMP" "INTERNET MODEM GG -007/PÓS/SMP" 
                "INTERNET MODEM M - 005/PÓS/SMP" "INTERNET MODEM P - 004/PÓS/SMP" "INTERNET TABLET - 008/PÓS/SMP" 
                "INTERNET MODEM P PROMO**" "INTERNET MODEM P" "INTERNET MODEM M PROMO**" "INTERNET MODEM M" 
                "INTERNET MODEM G PROMO**" "INTERNET MODEM G" "INTERNET MODEM GG PROMO**" "INTERNET MODEM GG" 
                "3G MODEM 1 GB" "3G + INT MODEM 3GB" "3G + INT MODEM 5GB" "3G +INT MODEM 8GB" "3G + INT MODEM 10GB" 
                "4G INT MODEM 3GB" "4G INT MODEM 5GB" "4G INT MODEM 8GB" "4G INT MODEM 10GB" "3G PLANO TESTE" 
                "INTERNET MODEM VIP" "INTERNET MODEM GERÊNCIA" "004/INTERNET MODEM P" "004/INTERNET MODEM P PROMO" 
                "004/POS/SMP - INTERNET MODEM" "005/INTERNET MODEM M" "005/INTERNET MODEM M PROMO" "007/INTERNET MODEM GG" 
                "3G MODEM 1GB 085/PÓS/SMP" "3G MODEM 1GB PJ 085/PÓS/SMP" "3G MODEM 2GB 085/PÓS/SMP" "3G MODEM 4GB 085/PÓS/SMP" 
                "3G MODEM PROMO 1GB 085/PÓS/SMP" "3G MODEM PROMO 2GB 085/PÓS/SMP" "3G MODEM PROMO 4GB 085/PÓS/SMP" 
                "3G+ INT MODEM 10GB 081/PÓS/SMP" "3G+ INT MODEM 3GB 081/PÓS/SMP" "3G+ INT MODEM 5GB 081/PÓS/SMP" 
                "3G+ INT MODEM 8GB 081/PÓS/SMP" "4G INT MODEM 10GB 076/PÓS/SMP" "4G INT MODEM 3GB 073/PÓS/SMP" 
                "4G INT MODEM 5GB 074/PÓS/SMP" "4G INT MODEM 8GB 075/PÓS/SMP" "INTERN MODEM G PJ 017/PÓS/SMP" 
                "INTERN MODEM GG PJ 016/PÓS/SMP" "INTERN MODEM M PJ 018/PÓS/SMP" "INTERN MODEM P PJ 019/PÓS/SMP" 
                "INTERNET MODEM COLABORADORES" "INTERNET MODEM FF 005/PÓS/SMP" "INTERNET MODEM FAMILIAR 3G" 
                "INTERNET MODEM G - 006/PÓS/SMP" "INTERNET MODEM GG -016/PÓS/SMP" "INTERNET MODEM GERÊNCIA" 
                "INTERNET MODEM M - 005/PÓS/SMP" "INTERNET MODEM P - 004/PÓS/SMP" "INTERNET MODEM TESTE" 
                "INTERNET MODEM VIP" "3G MODEM 1GB 085/POS/SMP" "3G MODEM 1GB PJ 085/POS/SMP" 
                "3G MODEM 2GB 085/POS/SMP" "3G MODEM 4GB 085/POS/SMP" "3G MODEM PROMO 1GB 085/POS/SMP" 
                "3G MODEM PROMO 4GB 085/POS/SMP" "3G+ INT MODEM 10GB 081/POS/SMP" "3G+ INT MODEM 3GB 081/POS/SMP" 
                "3G+ INT MODEM 5GB 081/POS/SMP" "3G+ INT MODEM 8GB 081/POS/SMP" "4G INT MODEM 10GB 076/POS/SMP" 
                "4G INT MODEM 3GB 073/POS/SMP" "4G INT MODEM 5GB 074/POS/SMP" "4G INT MODEM 8GB 075/POS/SMP" 
                "INTERN MODEM G PJ 017/POS/SMP" "INTERN MODEM GG PJ 016/POS/SMP" "INTERN MODEM M PJ 018/POS/SMP" 
                "INTERN MODEM P PJ 019/POS/SMP" "INTERNET MODEM COLABORADORES" "INTERNET MODEM FAMILIAR 3G" 
                "INTERNET MODEM FF 005/POS/SMP" "INTERNET MODEM G - 006/POS/SMP" "INTERNET MODEM GG -016/POS/SMP" 
                "INTERNET MODEM M - 005/POS/SMP" "INTERNET MODEM P - 004/POS/SMP")
            GROUP BY 1,2,3,4,5,6;
RUN;

DATA REPORT.BASE_3;
    SET REPORT.BASE_3;
    FORMAT CPF 16.;
    CPF = INPUT(C_CODI,BEST16.);
RUN;