/*LIBNAME ATIVA BASE "\\tsclient\S\BD_ATIVA";
LIBNAME ESCOBS BASE "\\tsclient\S\BD_ESCOB";
LIBNAME STOP BASE "\\tsclient\S\SUSPENSION";	 
LIBNAME DEACTS BASE "\\tsclient\S\DEACTS";	 
LIBNAME SPEC BASE "\\tsclient\S\SPEC";	
LIBNAME REPORT BASE "\\tsclient\S\REPORT;


LIBNAME ESCOBS BASE "S:\BD_ESCOB";
LIBNAME ATIVA BASE "S:\BD_ATIVA";
LIBNAME ESCOBS BASE "S:\BD_ESCOB";
LIBNAME STOP BASE "S:\SUSPENSION";	 
LIBNAME DEACTS BASE "S:\DEACTS";	 
LIBNAME SPEC BASE "S:\SPEC";	
LIBNAME REPORT BASE "\S:\REPORT";*/


LIBNAME ESCOBS BASE "C:\SAS\Libname\ESCOBS";
LIBNAME ATIVA BASE "C:\SAS\Libname\ATIVA";
LIBNAME REPORT BASE "C:\SAS\Libname\REPORT";
LIBNAME STOP BASE "C:\SAS\Libname\SUSPENSION";
LIBNAME DEACTS BASE "C:\SAS\Libname\DEACTS";

LIBNAME ESCOBS BASE "S:\ESCOBS";
LIBNAME ATIVA BASE "S:\ATIVA";
LIBNAME REPORT BASE "S:\REPORT";
LIBNAME STOP BASE "S:\SUSPENSION";
LIBNAME DEACTS BASE "S:\DEACTS";

LIBNAME ESCOBS BASE '\\Brsao3w7453268\sas\ESCOBS';
LIBNAME REPORT BASE '\\Brsao3w7453268\sas\REPORT';
"LIBNAME DIALER BASE "\\Brsao3W7453268\S\DIALER"
"LIBNAME ATIVA BASE "\\Brsao3W7453268\S\ATIVA"

