%LET _CLIENTTASKLABEL='PROGRAM11';
%LET _CLIENTPROJECTPATH='C:\USERS\VPASSIN2\DOCUMENTS\ESTUDOS DIVERSOS4.EGP';
%LET _CLIENTPROJECTNAME='ESTUDOS DIVERSOS4.EGP';
%LET _SASPROGRAMFILE=;

GOPTIONS ACCESSIBLE;
*ANÁLISE DO MÊS DE JANEIRO;

*1.CRUZANDO PRECHURN COM CHURN;

PROC SQL;
CREATE TABLE TBRESJANEIRO_1 AS
SELECT A.*, B.DEACTS
FROM COLLEC.TBPRECHURN201501_1 AS A
LEFT JOIN DEACT.DEACTS_201501 AS B ON A.IDCLIENTE = B.IDCLIENTE AND A.IDCONTRACT = B.IDCONTRATO AND B.DEACTS = 1
;
QUIT;

PROC FREQ DATA=TBRESJANEIRO_1;
TABLE DEACTS / NOCUM MISSING ;
RUN;


*2. CRUZANDO COM OS NÃO DESATIVADOS;
PROC IMPORT 
DATAFILE="E:\WORK\NEXTEL\DATA\EXPORTS\PRECHURN\PRE CHURN JANEIRO NÃO DESATIVADO.CSV" 
OUT=BACKLOG DBMS=DLM REPLACE;
DELIMITER=';';
GETNAMES=YES;
RUN;

PROC SQL;
CREATE TABLE TBRESJANEIRO_2 AS
SELECT A.*, B.FLGBACKLOG
FROM TBRESJANEIRO_1 AS A
LEFT JOIN BACKLOG AS B
ON A.IDCLIENTE = B.IDCLIENTE AND A.IDCONTRACT = B.IDCONTRACT
WHERE A.DEACTS = .
;
QUIT;

PROC FREQ DATA=TBRESJANEIRO_2;
TABLE FLGBACKLOG / NOCUM MISSING ;
RUN;

*3.DE QUEM SOBROU, QUERO VER QUEM FOI REATIVADO;;
PROC SQL;
CREATE TABLE TBRESJANEIRO_3 AS
SELECT A.*, B.DATA_REATIVACAO
FROM TBRESJANEIRO_2 AS A
LEFT JOIN SUSPE.CACHE_REATIVACAO AS B ON A.IDCLIENTE = B.CLIENTE AND A.IDCONTRACT = B.CONTRATO 
	AND B.DATA_REATIVACAO BETWEEN INPUT('01/01/2015', DDMMYY10.) AND INPUT('31/01/2015', DDMMYY10.)
WHERE A.DEACTS = . AND A.FLGBACKLOG = .
;
QUIT;

PROC SORT DATA=TBRESJANEIRO_3 NODUPKEY ; BY IDCLIENTE IDCONTRACT; RUN;

PROC FREQ DATA=TBRESJANEIRO_3;
TABLE DATA_REATIVACAO / NOCUM MISSING ;
RUN;

*3. QUAIS REATIVAÇÕES SÃO DEVIDO AS BAIXAS;;
PROC SQL;
CREATE TABLE TBRESJANEIRO_4 AS
SELECT A.*, B.LOG
FROM TBRESJANEIRO_3 AS A
LEFT JOIN COLLEC.LOG_TBBAIXA AS B ON A.NU_BOND = B.NF AND A.NU_BOND_ITEM = B.PARCELA AND 
;
QUIT;

PROC SORT DATA=TBRESJANEIRO_4 NODUPKEY ; BY IDCLIENTE IDCONTRACT; RUN;

PROC FREQ DATA=TBRESJANEIRO_4;
TABLE DATA_REATIVACAO*LOG / NOCOL NOROW NOPERCENT NOCUM MISSING ;
RUN;

*4. BAIXA DO DIA 30/01;

PROC IMPORT 
DATAFILE="C:\VICTOR.PASSINI\02.PROJETOS\201501-AÇÕES EMERGENCIAIS DO CHURN\BAIXA_TITULOS_2ND.TXT" 
OUT=TB2NDBAIXA DBMS=DLM REPLACE;
DELIMITER=';';
GETNAMES=YES;
RUN;

DATA TB2NDBAIXA;
SET TB2NDBAIXA;
LOG_2ND = 'BAIXA';
RUN;

PROC SQL;
CREATE TABLE TBRESJANEIRO_5 AS
SELECT A.*, B.LOG_2ND
FROM TBRESJANEIRO_4 AS A
LEFT JOIN TB2NDBAIXA AS B ON A.NU_BOND = B.NF AND A.NU_BOND_ITEM = B.PARCELA 
;
QUIT;

DATA TBRESJANEIRO_6;
SET TBRESJANEIRO_5;
IF LOG NE '' THEN BAIXA = 1;
IF LOG_2ND NE '' THEN BAIXA = 1;
RUN;

PROC FREQ DATA=TBRESJANEIRO_6;
TABLE DATA_REATIVACAO*BAIXA / NOCOL NOROW NOPERCENT NOCUM MISSING ;
RUN;


GOPTIONS NOACCESSIBLE;
%LET _CLIENTTASKLABEL=;
%LET _CLIENTPROJECTPATH=;
%LET _CLIENTPROJECTNAME=;
%LET _SASPROGRAMFILE=;

