%LET MDATE = '20MAR2013'D;

/*MIS_DATE D-1*/
PROC SQL; /*SELECIONA CASOS DO SKIP NO CACS*/
	CREATE TABLE SASUSER.SKIP_CACS AS SELECT DISTINCT
		DATEPART (A.MIS_DATE) FORMAT DATE9. AS DATA,
		A.C_P_LOCATION_CODE,
		A.C_P_ACCT_NBR,
		A.C_P_CACS_STATE_CODE,
		B.C_E_SERVICE_TYPE,
		B.C_E_CUST_INFO_NBR,
		B.C_E_TOTAL_DUE_AMT

	FROM BRDBCON.DRI_076_ECS_COLL_PRI_ED AS A
		INNER JOIN BRDBCON.DRI_076_ECS_COLL_EXT_ED_VG3 AS B
			ON A.MIS_DATE = B.MIS_DATE AND A.C_P_ACCT_NBR = B.C_E_ACCT_NBR
		WHERE A.MIS_DATE = &MDATE 
			AND (A.C_P_CACS_STATE_CODE LIKE "%07" 
			OR A.C_P_CACS_STATE_CODE LIKE "%08")
			/*OR A.C_P_CACS_STATE_CODE LIKE "%09")
			AND B.C_E_TOTAL_DUE_AMT > 100.00*/
	ORDER BY B.C_E_TOTAL_DUE_AMT;
RUN;

PROC SQL; /*SELECIONA CASOS DO SKIP NO E5*/
	CREATE TABLE SASUSER.SKIP_E5 AS SELECT DISTINCT
		DATEPART (C.MIS_DATE) FORMAT DATE9. AS DATA,
		C.HST_DW_ORG AS ORG_SKIP,
		C.HST_DW_CARD_NBR AS CARTAO_SKIP,
		C.HST_DW_TYPE AS TYPE_SKIP,
		C.HST_DW_TAX_ID AS CPF_SKIP,
		C.HST_DW_STATUS_SKIP AS STATUS_SKIP,
		C.HST_DW_DISCARD_REASON AS DISCARD_REASON_SKIP

	FROM BRDBCON.DRI_076_ECS_SKIP_TRAC_ED AS C
		WHERE C.MIS_DATE = &MDATE 
			/*AND C.HST_DW_STATUS_SKIP <> 'N'*/
	AND C.HST_DW_TYPE = 6
	AND C.HST_DW_ORG IN (380,381);
RUN;

PROC SQL;
	CREATE TABLE SASUSER.SKIP AS SELECT
		*
	FROM SASUSER.SKIP_CACS AS A LEFT JOIN SASUSER.SKIP_E5 AS B
		ON A.DATA = B.DATA AND A.C_P_ACCT_NBR = B.CARTAO_SKIP
		/*WHERE B.CARTAO_SKIP IS NULL*/;
RUN;

PROC SQL; /*SELECIONA CASOS NO CACS SKIP SÓ QUE FORA DO E5*/
	CREATE TABLE SASUSER.FORA_E5 AS SELECT
		*
	FROM SASUSER.SKIP
		WHERE CARTAO_SKIP IS NULL;
RUN;

PROC SQL; /*SELECIONA CASOS DISCARTED NO E5 E NA FILA DO CACS*/
	CREATE TABLE SASUSER.DISCARTED AS SELECT
		*
	FROM SASUSER.SKIP
		WHERE STATUS_SKIP = 'D';
RUN;

PROC SQL; /*SELECIONA CASOS CLOSED NO E5 E NA FILA DO CACS*/
	CREATE TABLE SASUSER.CLOSED AS SELECT
		*
	FROM SASUSER.SKIP
		WHERE STATUS_SKIP = 'C';
RUN;

PROC SQL; /*SELECIONA CASOS WORKED NO E5 E NA FILA DO CACS*/
	CREATE TABLE SASUSER.WORKED AS SELECT
		*
	FROM SASUSER.SKIP
		WHERE STATUS_SKIP = 'W';
RUN;

PROC SQL; /*FINAL PARA RODAR ROBO*/
	CREATE TABLE SASUSER.RODAR_ROBO_SKIP_X25 AS SELECT
		A.C_P_LOCATION_CODE, A.C_P_ACCT_NBR, A.C_P_CACS_STATE_CODE, A.C_E_CUST_INFO_NBR,
		A.TYPE_SKIP, A.STATUS_SKIP

	FROM SASUSER.DISCARTED AS A

		UNION

	SELECT B.C_P_LOCATION_CODE, B.C_P_ACCT_NBR, B.C_P_CACS_STATE_CODE, B.C_E_CUST_INFO_NBR,
		B.TYPE_SKIP, B.STATUS_SKIP

	FROM SASUSER.CLOSED AS B

		UNION

	SELECT C.C_P_LOCATION_CODE, C.C_P_ACCT_NBR, C.C_P_CACS_STATE_CODE, C.C_E_CUST_INFO_NBR,
		C.TYPE_SKIP, C.STATUS_SKIP

	FROM SASUSER.WORKED AS C
		ORDER BY STATUS_SKIP;
QUIT;