/*****************************************************************************
 ******************************************************************************
 ***********                                                     **************
 ********         GERACAO DA BASE FINAL - REPORT AGENCIAS           ***********
 ***********                                                      *************
 ******************************************************************************
 ******************************************************************************/
DATA SASUSER.REMESSA_EX;/* 1.1 CAPTURANDO INFO DE REMESSA */
	SET
		ESCOBS.BDESCOB_201505
		ESCOBS.BDESCOB_201506;
	WHERE BASE = 'REMESSA EX' 
		AND STATUS = "REMESSA";
RUN;

DATA REPORT.BAIXA_EX;/* 1.2 CAPTURANDO INFO DE BAIXA */
	SET      
		ESCOBS.BDESCOB_201505
		ESCOBS.BDESCOB_201506;
	WHERE BASE IN ('BAIXA_EX' 'BAIXA EX')
		AND STATUS <> "REMESSA";
RUN;

PROC SORT/* ORDENANDO BASE */

	DATA = SASUSER.REMESSA_EX;
	BY C_CODI DATA_ARQUIVO P_TITULO;
RUN;

PROC SORT/* VERIFICANDO DUPLICIDADE*/

	DATA= SASUSER.REMESSA_EX 
		NODUPKEY;
	BY C_CODI P_TITULO VENC_TITULO;
RUN;

PROC SORT/* ORDENANDO BASE */

	DATA = REPORT.BAIXA_EX;
	BY C_CODI DATA_ARQUIVO P_TITULO;
RUN;

PROC SORT/* VERIFICANDO DUPLICIDADE*/

	DATA= REPORT.BAIXA_EX 
		NODUPKEY;
	BY C_CODI P_TITULO;
RUN;

PROC SQL;
	CREATE TABLE REPORT.REMESSA_EX AS SELECT

		A.*,
		B.P_TITULO AS PRECHURN,
		B.IDCONTRACT


	FROM SASUSER.REMESSA_EX AS A LEFT JOIN REPORT.PRECHURN_ESCOBS AS B ON A.IDCLIENTE = B.IDCLIENTE 
		AND A.P_TITULO = B.P_TITULO	/*AND B.DATA_VENC = A.VENC_TITULO*/;
RUN;

DATA REPORT.REMESSA_EX;
	SET REPORT.REMESSA_EX;
	FORMAT CHURN $4.;

	IF PRECHURN = P_TITULO THEN
		CHURN = "SIM";
RUN;

PROC TRANSPOSE /* TRANSPOR DE LINHA PARA COLUNA*/

	DATA     = REPORT.BAIXA_EX                /* LIB.NOME_BASE - LEITURA */
	OUT      = REPORT.BAIXA_EX_1( DROP= _NAME_)
		PREFIX   = BAIXA_;                        /* LIB.NOME_TABELA - CRIAR */
	BY        C_CODI P_TITULO;                         /* VARIAVEIS QUE SERAO MANTIDAS NA LINHA */
	ID        C_MOTIVO_BXA;                   /* VARIAVEL A SER COLUNADA */
	VAR       DATA_ARQUIVO;                   /* VARIAVEL CARREGADA NOS VALORES DAS COLUNAS TABULADAS */
RUN;

PROC SQL;/* CRUZANDO INFO PART_1*/
	CREATE TABLE REPORT.BASE_7 AS SELECT
		*
	FROM REPORT.REMESSA_EX AS A LEFT JOIN  REPORT.BAIXA_EX_1 AS B ON A.C_CODI = B.C_CODI 
		AND A.P_TITULO = B.P_TITULO;
RUN;

DATA REPORT.BASE_8;/* FORMATACAO E PRIORIZACAO*/
	SET  REPORT.BASE_7;
	FORMAT DAT_PRIOR DATA_ARQUIVO DDMMYY10.;

	IF BAIXA_PG <> . THEN
		DAT_PRIOR = BAIXA_PG;
	ELSE IF BAIXA_DP <> . THEN
		DAT_PRIOR = BAIXA_DP;

	IF BAIXA_PG <> . THEN
		PRIOR = 'PG';
	ELSE IF BAIXA_DP <> . THEN
		PRIOR = 'DP';
	DATE_NEW = COMPRESS(YEAR(DATA_ARQUIVO)*10000+ MONTH(DATA_ARQUIVO)*100+ DAY(DATA_ARQUIVO));
	VALOR = C_VPAR*1;
RUN;

DATA REPORT.BASE_9;
	SET REPORT.BASE_8;
	FORMAT MOTIVO_BAIXA $4.;
	FORMAT SAFRA_BASE $10.;
	FORMAT SAFRA_ARQ $6.;
	FORMAT SAFRA_PGTO $6.;

	IF PRIOR = "PG" THEN
		MOTIVO_BAIXA = "PG";
	ELSE IF PRIOR = "OT" THEN
		MOTIVO_BAIXA = "OT";
	ELSE IF PRIOR = "DP" THEN
		MOTIVO_BAIXA = "DP";
	ELSE IF PRIOR = "" THEN
		MOTIVO_BAIXA = "NULL";
	SAFRA_ARQ = YEAR(DATA_ARQUIVO)*100 + MONTH(DATA_ARQUIVO);
	SAFRA_PGTO = YEAR(DAT_PRIOR)*100 + MONTH(DAT_PRIOR);

	IF  BASE = "REMESSA UI" THEN
		SAFRA_BASE = "REMESSA UI";
	ELSE IF BASE = "REMESSA" THEN
		SAFRA_BASE = "REMESSA";
	ELSE IF BASE = "REMESSA COMP" THEN
		SAFRA_BASE = "REMESSA";
	ELSE IF BASE = "REMESSA XB" THEN
		SAFRA_BASE = "REMESSA XB";
	ELSE IF BASE = "REMESSA EX" THEN
		SAFRA_BASE = "REMESSA EX";
RUN;
 *RODAR A QUERY GERA_BD_D4;

PROC SQL;
	*GERA A BASE FINAL;
	CREATE TABLE REPORT.BASE_ESCOBS_EX AS 
		SELECT

			A.DATE_NEW AS DATE_ARQ,
			A.PRIOR AS STATUS,
			A.TIPO,
			A.BASE,
			A.ESCOB,
			COUNT(A.ESCOB)AS QUANT_TITULO,
			COUNT(A.CTR) AS QUANT_CONTRATO,
			SUM(A.VALOR) AS REC FORMAT COMMAX9.2,
			A.DAT_PRIOR,
			A.DATA_ARQUIVO,
			SAFRA_ARQ,
			SAFRA_PGTO,
			SAFRA_BASE,
			MOTIVO_BAIXA,
			FAIXA,
			MOB,
			TECNOLOGIA,
			BUCKET,
			AGING,
			SUBSTR(C_NUMT,7,2)AS ESPECIE FORMAT $3.,
			BILLING,
			CHURN

		FROM REPORT.BD_D4_EX AS A

		GROUP BY 1,2,3,4,5,9,10,11,12,13,14,15,16,17,18,19,20,21,22;
RUN;

PROC APPEND	 
DATA=REPORT.BASE_ESCOBS   
BASE=REPORT.BASE_ESCOBS_EX	 
FORCE;
RUN;

PROC EXPORT DATA= REPORT.BASE_ESCOBS_EX /*EXPORT DA BASE FINAL PARA CARREGAR O REPORT DAS AGENCIAS*/
	OUTFILE= "\\BRSLP1W8PFS03\GRUPOS\AFINIDADE\PLANEJAMENTO_CREDITO_COBRANCA\008_M.I.S\03_BOOK_ESCOBS\TXT\BASE_ESCOBS.TXT"
		DBMS=TAB 
		REPLACE;
RUN;

/*PROC SQL;
CREATE TABLE REPORT.BASE_11 AS SELECT DISTINCT

A.*,
MAX(B.ESCOB) AS REMESSA_COMP,
B.DATA_ARQUIVO AS ENVIO_COMP,
B.MOTIVO_BAIXA AS BAIXA_COMP,
B.DAT_PRIOR	 AS DATA_BX_COMP

FROM REPORT.BASE_FINAL AS A LEFT JOIN REPORT.BASE_6_2 AS B ON A.IDCLIENTE = B.IDCLIENTE 
AND A.P_TITULO = B.P_TITULO 
AND A.DATA_VENC = B.VENC_TITULO
GROUP BY 1,3,4
ORDER BY IDCONTRACT DESC;
WHERE DAT_PRIOR <='01JUN2015'D;
RUN;

PROC SQL;
CREATE TABLE REPORT.BASE_12 AS SELECT DISTINCT

A.*,
B.ESCOB AS REMESSA_EX,
B.DATA_ARQUIVO AS ENVIO_EX,
B.MOTIVO_BAIXA AS BAIXA_EX,
B.DAT_PRIOR AS DATA_BX_EX


FROM REPORT.BASE_11 AS A LEFT JOIN REPORT.BASE_6_4 AS B ON A.IDCLIENTE = B.IDCLIENTE 
AND A.P_TITULO = B.P_TITULO;
RUN;


PROC APPEND 
DATA=REPORT.BASE_ESCOBS_EX 
BASE=REPORT.BASE_ESCOBS 
FORCE;
RUN;