/* CAPTURANDO BASE DE REMESSA */
DATA BASE_REMESSA;
SET  ESCOBS.BDESCOB_201401;
WHERE BASE IN ('REMESSA' 'REMESSA COMP');
RUN;

DATA BASE_BAIXA;
SET  ESCOBS.BDESCOB_201401;
WHERE BASE IN ('BAIXA');
RUN;

DATA BASE_PRESTACAO;
SET  /*ESCOBS.BDPRESTACAO_201312*/
	 ESCOBS.BDPRESTACAO_201401;
WHERE P_DLETRA <> "";
RUN;

/* CONFERINDO DUPLICIDADES */
	/* REMESSA */
PROC SORT DATA= BASE_REMESSA;
BY C_ID_EMP DATA_ARQUIVO;
RUN;

PROC SORT DATA= BASE_REMESSA NODUPKEY;
BY C_ID_EMP;
RUN;

	/* BAIXA */
PROC SORT DATA= BASE_BAIXA;
BY C_ID_EMP DATA_ARQUIVO;
RUN;

PROC SORT DATA= BASE_BAIXA NODUPKEY;
BY C_ID_EMP;
RUN;

	/* PRESTACAO */
PROC SORT DATA= BASE_PRESTACAO;
BY P_ID_EMP DATA_ARQUIVO;
RUN;

PROC SORT DATA= BASE_PRESTACAO NODUPKEY;
BY P_ID_EMP;
RUN;

/* CRUZANDO INFO */
PROC SQL;
CREATE TABLE BASE_1 AS
SELECT 
A.C_ID_EMP AS ID_ORIGEM,
B.C_ID_EMP AS ID_BX,
B.STATUS   AS STATUS_BX 
FROM BASE_REMESSA AS A 
LEFT JOIN
BASE_BAIXA AS B
ON A.C_ID_EMP = B.C_ID_EMP;
RUN;

PROC SQL;
CREATE TABLE BASE_2 AS
SELECT 
A.*,
B.P_ID_EMP AS ID_PREST,
B.STATUS   AS STATUS_PREST 
FROM BASE_1 AS A 
LEFT JOIN
BASE_PRESTACAO AS B
ON A.ID_ORIGEM = B.P_ID_EMP;
RUN;








/* VERIFICANDO DUPLICIDADES */
PROC SORT DATA=BASE_REMESSA;
BY C_ID_EMP;
RUN;

PROC SQL;
CREATE TABLE BASE_BAIXA1 AS 
SELECT
C_ID_EMP,
COUNT(C_ID_EMP) AS QTD
FROM BASE_BAIXA
GROUP BY C_ID_EMP
HAVING(COUNT(C_ID_EMP)>1);
RUN;
QUIT;


PROC SQL;
CREATE TABLE BASE_BAIXA2 AS
SELECT 
* FROM BASE_BAIXA1 AS A
LEFT JOIN
BASE_BAIXA AS B
ON A.C_ID_EMP = B.C_ID_EMP;
RUN;
QUIT;

