/**********************************************************************************
 ***********************************************************************************
 ***************************RECUPERACAO BACKLOG ANTERIOR****************************
 ***********************************************************************************
 ***********************************************************************************/
%LET TEC_2G_INCIAL = '03NOV2014'D;
%LET TEC_2G_FINAL  = '02DEC2014'D;
%LET TEC_3GT_INICIAL ='18NOV2014'D;
%LET TEC_3GT_FINAL =  '16DEC2014'D;
%LET TEC_3GP_INICIAL ='18OCT014'D;
%LET TEC_3GP_FINAL =  '17NOV2014'D;

PROC SQL;/*BACKLOG INICIAL 318 = IN-SUSPENSAO PARCIAL 230 = IN-NAO PAGAMENTO*/

    CREATE TABLE REPORT.BCKL_INICIAL AS
        SELECT

            INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
            INPUT(CONTRACT,8.) AS IDCONTRACT,
            DTSUSPENSION,
            TECHNOLOGY_TYPE,('IDEN|PARCIAL') AS TIPO  
        FROM ESCOBS.BACKLOG_201412
            WHERE TECHNOLOGY_TYPE = 'IDEN' AND  DTSUSPENSION BETWEEN  &TEC_2G_INCIAL AND &TEC_2G_FINAL
                AND CONTRACT_REASON_STATUS = '318'  
                UNION ALL


            SELECT

                INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
                INPUT(CONTRACT,8.) AS IDCONTRACT,
                DTSUSPENSION,
                TECHNOLOGY_TYPE ,('3G|PARCIAL') AS TIPO 
            FROM ESCOBS.BACKLOG_201412
                WHERE TECHNOLOGY_TYPE = '3G' AND  DTSUSPENSION BETWEEN  &TEC_3GP_INICIAL AND &TEC_3GP_FINAL
                    AND CONTRACT_REASON_STATUS = '318'  
                    UNION ALL



                SELECT

                    INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
                    INPUT(CONTRACT,8.) AS IDCONTRACT,
                    DTSUSPENSION,
                    TECHNOLOGY_TYPE,('3G|TOTAL') AS TIPO   
                FROM ESCOBS.BACKLOG_201412
                    WHERE TECHNOLOGY_TYPE = '3G' AND  DTSUSPENSION BETWEEN &TEC_3GT_INICIAL AND &TEC_3GT_FINAL
                        AND CONTRACT_REASON_STATUS = '230';
RUN;

PROC SQL;/*BACKLOG ATUAL 318 = IN-SUSPENSAO PARCIAL 230 = IN-NAO PAGAMENTO*/

    CREATE TABLE REPORT.BCKL_ATUAL AS
        SELECT

            INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
            INPUT(CONTRACT,8.) AS IDCONTRACT,
            DTSUSPENSION,
            TECHNOLOGY_TYPE,('IDEN|PARCIAL') AS TIPO  
        FROM ESCOBS.BACKLOG_201501
            WHERE TECHNOLOGY_TYPE = 'IDEN' AND  DTSUSPENSION BETWEEN  &TEC_2G_INCIAL AND &TEC_2G_FINAL
                AND CONTRACT_REASON_STATUS = '318'  
                UNION ALL


            SELECT

                INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
                INPUT(CONTRACT,8.) AS IDCONTRACT,
                DTSUSPENSION,
                TECHNOLOGY_TYPE ,('3G|PARCIAL') AS TIPO 
            FROM ESCOBS.BACKLOG_201501
                WHERE TECHNOLOGY_TYPE = '3G' AND  DTSUSPENSION BETWEEN  &TEC_3GP_INICIAL AND &TEC_3GP_FINAL
                    AND CONTRACT_REASON_STATUS = '318'  
                    UNION ALL



                SELECT

                    INPUT(CUSTOMER_TAX_NUMBER,BEST14.) AS IDCLIENTE,
                    INPUT(CONTRACT,8.) AS IDCONTRACT,
                    DTSUSPENSION,
                    TECHNOLOGY_TYPE,('3G|TOTAL') AS TIPO   
                FROM ESCOBS.BACKLOG_201501
                    WHERE TECHNOLOGY_TYPE = '3G' AND  DTSUSPENSION BETWEEN &TEC_3GT_INICIAL AND &TEC_3GT_FINAL
                        AND CONTRACT_REASON_STATUS = '230';
RUN;

DATA REPORT.SUSPENSAO;*CONSTRUINDO A BASE DE SUSPENSÃO DOIS ÚLTIMOS 3 MESES;
    SET ESCOBS.SUSPENSION_201410 ESCOBS.SUSPENSION_201411 ESCOBS.SUSPENSION_201412;
    IF DATA_SUSPENSAO NE .;

                RENAME 
                    CD_CUSTOMER_BOND_KIND =  ESPECIE
                    NR_CUSTOMER_BOND = NU_BOND
                    NR_CUSTOMER_ITEM = NU_BOND_ITEM
                    DT_CUSTOMER_BOND_DUE_DATE = DATA_VENCIMENTO
                    BOND_ORIGINAL_VALOR = VLR_BOND;
                KEEP 
                    CLIENTE CONTRATO 
                    PLANO DATA_SUSPENSAO 
                    CD_CUSTOMER_BOND_KIND
                    NR_CUSTOMER_BOND 
                    NR_CUSTOMER_ITEM 
                    DT_CUSTOMER_BOND_DUE_DATE
                    BOND_ORIGINAL_VALOR 
                    CUSTOMER_ACCOUNT 
                    CREDIT_SCORE 
                    CD_REASON REASON;
RUN;
PROC SQL;
    CREATE TABLE REPORT.BCKL_ATUAL_ANALITICA AS
        SELECT 
            A.*, 
            B.CUSTOMER_ACCOUNT, 
            B.PLANO, 
            B.DATA_SUSPENSAO, 
            B.CD_REASON, 
            B.REASON,
            B.ESPECIE, 
            B.NU_BOND, 
            B.NU_BOND_ITEM, 
            B.DATA_VENCIMENTO, 
            B.VLR_BOND, 
            B.CREDIT_SCORE
        FROM REPORT.BCKL_ATUAL AS A LEFT JOIN REPORT.SUSPENSAO AS B ON A.IDCLIENTE = B.CLIENTE AND A.IDCONTRACT = B.CONTRATO;
QUIT;

PROC EXPORT DATA=TBBACKLOG201501_ANALITICA
    OUTFILE='\\Brslp1w8pfs03\grupos\Afinidade\Planejamento_Credito_Cobranca\008_M.I.S\05_DEACTS\BACKLOG201501_ANALITICA.CSV'
    DBMS=CSV
    REPLACE;
RUN;

PROC SORT/*IDENTIFICANDO OS CLIENTES QUE SAIRAM DO BACKLOG, ISTO E, CRUZAR QUEM INICIOU CONTRA QUEM SAIU*/

    DATA=REPORT.BCKL_INICIAL;
    BY IDCONTRACT;
RUN;

PROC SORT/*IDENTIFICANDO OS CLIENTES QUE SAIRAM DO BACKLOG, ISTO E, CRUZAR QUEM INICIOU CONTRA QUEM SAIU*/

    DATA=REPORT.BCKL_ATUAL;
    BY IDCONTRACT;
RUN;

DATA RECOVERY_1;
    MERGE REPORT.BCKL_INICIAL (IN=A) REPORT.BCKL_ATUAL (IN=B);
    BY IDCONTRACT;

    IF B=0;
RUN;

PROC SQL;
    CREATE TABLE RECOVERY_2 AS
        SELECT 

            A.*, 
            B.CLASS_TIPO

        FROM RECOVERY_1 AS A LEFT JOIN ESCOBS.DEACTS_201501 AS B ON A.IDCONTRACT = B.CONTRACT;
QUIT;

PROC FREQ 
    DATA=RECOVERY_2;
    TABLE CLASS_TIPO / NOCOL NOROW NOCUM MISSING;
RUN;

DATA REATIVACAO;
    SET ESCOBS.SUSPENSION_201501;

    IF DATA_REATIVACAO_ANTERIOR NE . OR DATA_REATIVACAO_NO_MES NE .;
    FLGREATIV = 1;
    KEEP CLIENTE CONTRATO DATA_BASE DATA_REATIVACAO_ANTERIOR DATA_REATIVACAO_NO_MES  TYPE_TECHNOLOGY;
    RUN;

PROC SORT 
    DATA  = REATIVACAO;
    BY CLIENTE CONTRATO
        DESCENDING DATA_BASE;
RUN;
PROC SORT 
    DATA  = REATIVACAO 
    NODUPKEY;
    BY CLIENTE CONTRATO;
RUN;
PROC SQL;/*IDENTIFICANDO OS CLIENTES QUE SAIRAM DO BACKLOG, ISTO E, CRUZAR QUEM INICIOU CONTRA QUEM SAIU*/;
    CREATE TABLE RECOVERY_3 AS
        SELECT 

            A.*, 
            B.DATA_BASE AS DTREATIVACAO 

        FROM RECOVERY_2 AS A LEFT JOIN REATIVACAO AS B ON A.IDCONTRACT = B.CONTRATO;
RUN;
PROC FREQ/*REPORT FINAL*/

    DATA=RECOVERY_3;
    WHERE CLASS_TIPO = '' 
        AND MONTH (DTREATIVACAO) = 12;

    TABLE DTREATIVACAO * TECHNOLOGY_TYPE / 
        NOCOL NOPERCENT NOROW NOCUM MISSING;
RUN;
 /**********************************************************************************
 ***********************************************************************************
 ***************************RECUPERACAO BACKLOG ATUAL*******************************
 ***********************************************************************************
 ***********************************************************************************/
DATA BD_REATIVACAO;
    SET ESCOBS.SUSPENSION_201501;

    IF DATA_REATIVACAO_ANTERIOR NE . OR DATA_REATIVACAO_NO_MES NE .;
    FLGREATIV = 1;
    KEEP CLIENTE CONTRATO DATA_BASE DATA_REATIVACAO_ANTERIOR DATA_REATIVACAO_NO_MES TYPE_TECHNOLOGY;
RUN;
      DATA BD_SUSPENSAO_MES;
    SET ESCOBS.SUSPENSION_201501;

    IF DATA_SUSPENSAO NE .;

    *IF IDCONTRACT_REASON_STATUS IN (318, 230);
    KEEP CLIENTE CONTRATO DATA_BASE DATA_SUSPENSAO TYPE_TECHNOLOGY REASON;
RUN;

PROC SORT 
    DATA=BD_REATIVACAO;
    BY CLIENTE CONTRATO 
        DESCENDING DATA_BASE;
RUN;

PROC SORT 
    DATA=BD_REATIVACAO 
    NODUPKEY;
    BY CLIENTE CONTRATO;
RUN;

PROC SORT 
    DATA=BD_SUSPENSAO_MES;
    BY CLIENTE CONTRATO 
        DESCENDING DATA_BASE;
RUN;

PROC SORT 
    DATA=BD_SUSPENSAO_MES 
    NODUPKEY;
    BY CLIENTE CONTRATO;
RUN;

PROC SQL;
    CREATE TABLE RECOVERY_4 AS

    SELECT 
        A.*, 
        B.CLASS_TIPO
    FROM BD_SUSPENSAO_MES AS A LEFT JOIN ESCOBS.DEACTS_201501 AS B ON A.CONTRATO = B.CONTRACT;
RUN;

PROC FREQ 
    DATA=RECOVERY_4;
    TABLE CLASS_TIPO / 
        NOCOL NOROW NOCUM MISSING;
RUN;

PROC SQL;
    CREATE TABLE RECOVERY_5 AS

    SELECT 
        A.*, 
        B.DATA_BASE AS DTREATIVACAO 
    FROM RECOVERY_4 AS A LEFT JOIN BD_REATIVACAO AS B ON A.CONTRATO = B.CONTRATO
    ;
QUIT;

PROC FREQ 
    DATA=RECOVERY_5;
    WHERE CLASS_TIPO = '' 
        AND MONTH (DATA_BASE) = 12;

    TABLE DTREATIVACAO * TYPE_TECHNOLOGY / 
        NOCOL NOPERCENT NOROW NOCUM MISSING;
RUN;